---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/docker/

my-docker:
    host: portainer
    port: <your port>

# my-docker:
#   socket: /var/run/docker.sock
